### ISSUE TITLE
Suggestion for the new hike page

### ISSUE THREAD

**Issue by Chicco1999** [marcomele98/HikeTracker_Group05#19]
Hi, I would like to leave some feedback about the new hike feature: as a local guide, I have some experience working with coordinates, but I am not good enough to identify the location of a set of coordinates just by looking at the values. The interface is overall complete and intuitive but when I am defining the track of a new hike, I would like to be able to see on a map the location of the start, end and reference points that I am adding.

**Comment by FedericoRinaudi** [comment]
We will resolve that, but there is already another issue open with the same request

**Comment by FedericoRinaudi** [comment]
We will resolve that, but there is already another issue open with the same request
