### ISSUE TITLE
Feedback on demo 1

### ISSUE THREAD

**Issue by mistru97** [marcomele98/HikeTracker_Group05#20]
Here the list of feedback given after the sprint review of demo 1:
* As a Visitor that want to register into the software, I want to receive an email verification to ensure that the one inserted on the registration form is correct. This also protect the system from validate user based on fake/not owned email addresses.
* I liked that as a Local guide I can assign a point of interest directly from the provided gpx file and edit easily the information for a set of coordinates.

**Comment by FedericoRinaudi** [comment]
Thank you for your issue, we have updated the new's hike form.
A guide still select coordinates with a selector, but now is showed on the map the point that will be added before to confirm it.
In the next days we will add the verification for the email as you suggested.

**Comment by FedericoRinaudi** [comment]
Hi! we have added the email verification as requested.
We have improved the acquisition of reference points too.
We have also improved the acquisition of reference points compared to last week's comment, now to choose a reference point you can click directly on the map.
Thanks again for allowing us to improve HikeTracker
