### ISSUE TITLE
Feedback on Demo 1

### ISSUE THREAD

**Issue by francescofiorella** [marcomele98/HikeTracker_Group05#21]
## The things I like
I enjoyed how you managed the map and how the web page is responsive when creating the intermediate points of an hike.

## The issue
I think that the size of the font is too small, some people might have some problems in reading. Also, you can distribute better the text, like putting it in the middle of the page, instead of putting all of it in the left, leaving half of the page empty.

**Comment by FedericoRinaudi** [comment]
Thank you for your issue, we think that your observation is on point, but we think that for the moment there some stories and issue with higher priority, so it will not be implemented in the next sprints
